### PR TITLE
Rearranged job summary dashboard columns and make job_name clickable

### LINKED ISSUE #3261: [BUG]: Job summary has redundant and non-clickable columns
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

image

### Expected Behavior

_No response_

### Steps To Reproduce

_No response_

### Cloud

AWS

### Operating System

macOS

### Version

latest via Databricks CLI

### Relevant log output

_No response_

### PR DESCRIPTION
**Pull request by pritishpai**
## Changes
Rearranged job summary widget dashboard columns and make column name clickable

### Linked issues
Resolves #3261 

### Functionality

- [x] modified dashboard widget

### Tests
- [x] manually tested
- [x] verified on labs environment (screenshot attached)

### CODE REVIEW

**Comment by pritishpai** [comment]
job_summary_clickable

File: src/databricks/labs/ucx/queries/assessment/main/30_3_job_details.sql [hunk 1]
```diff
@@ -1,12 +1,26 @@
-/* --title 'Job Details' --filter job_name --width 6 */
+/*
+--title 'Job Details'
+--filter job_name
+--width 6
+--overrides '{"spec":{
+    "encodings":{
+      "columns": [
+        {"fieldName": "job_name", "booleanValues": ["false", "true"], "linkUrlTemplate": "/jobs/{{ job_id }}", "linkTextTemplate": "{{ @ }}", "linkTitleTemplate": "{{ @ }}", "linkOpenInNewTab": true, "type": "string", "displayAs": "link", "title": "job_name"},
+        {"fieldName": "job_id", "booleanValues": ["false", "true"], "type": "integer", "displayAs": "number", "title": "job_id"},
```
Comment (nfx) [inline src/databricks/labs/ucx/queries/assessment/main/30_3_job_details.sql:9]: mark job_id column as hidden

File: src/databricks/labs/ucx/queries/assessment/main/30_3_job_details.sql [hunk 2]
```diff
@@ -1,12 +1,26 @@
...
+        {"fieldName": "failures", "booleanValues": ["false", "true"], "type": "integer", "displayAs": "number", "title": "failures"},
+        {"fieldName": "creator", "booleanValues": ["false", "true"], "type": "string", "displayAs": "string", "title": "creator"}
+      ]}
+  }}'
+*/
 SELECT
-  job_id,
   job_name,
+  job_id,
   success,
```
Comment (nfx) [inline src/databricks/labs/ucx/queries/assessment/main/30_3_job_details.sql:19]:
```suggestion
```
success doesn't bring any clarity to this dashboards

File: src/databricks/labs/ucx/queries/assessment/main/30_3_job_details.sql [hunk 3]
```diff
@@ -1,12 +1,26 @@
-/* --title 'Job Details' --filter job_name --width 6 */
+/*
```
Comment (nfx) [inline src/databricks/labs/ucx/queries/assessment/main/30_3_job_details.sql:1]: actually, remove this widget altogether, because it's effectively a duplicate of `src/databricks/labs/ucx/queries/assessment/main/30_3_jobs.sql`

File: src/databricks/labs/ucx/queries/assessment/main/30_3_jobs.sql [hunk 4]
```diff
@@ -1,11 +1,23 @@
-/* --title 'Incompatible Jobs' --width 6 */
+/*
+--title 'Incompatible Jobs'
+--width 6
+--overrides '{"spec":{
+    "encodings":{
+      "columns": [
+        {"fieldName": "job_name", "booleanValues": ["false", "true"], "linkUrlTemplate": "/jobs/{{ job_id }}", "linkTextTemplate": "{{ @ }}", "linkTitleTemplate": "{{ @ }}", "linkOpenInNewTab": true, "type": "string", "displayAs": "link", "title": "job_name"},
+        {"fieldName": "job_id", "booleanValues": ["false", "true"], "type": "integer", "displayAs": "number", "title": "job_id"},
```
Comment (nfx) [inline src/databricks/labs/ucx/queries/assessment/main/30_3_jobs.sql:8]: mark as hidden

File: src/databricks/labs/ucx/queries/assessment/main/30_3_jobs.sql [hunk 5]
```diff
@@ -1,11 +1,23 @@
...
+        {"fieldName": "creator", "booleanValues": ["false", "true"], "type": "string", "displayAs": "string", "title": "creator"}
+      ]}
+  }}'
+*/
 SELECT
-  EXPLODE(FROM_JSON(failures, 'array<string>')) AS finding,
-  job_id,
   job_name,
+  job_id,
+  EXPLODE(FROM_JSON(failures, 'array<string>')) AS finding,
```
Comment (nfx) [inline src/databricks/labs/ucx/queries/assessment/main/30_3_jobs.sql:17]:
```suggestion
  EXPLODE(FROM_JSON(failures, 'array<string>')) AS problem,
```
better call it "problem"

**Review by nfx — DISMISSED** [review]
squash these two widgets into one.

**Comment by pritishpai** [comment]
image

File: src/databricks/labs/ucx/queries/assessment/main/30_3_jobs.sql (hunk 4 above)
Comment (pritishpai) [reply src/databricks/labs/ucx/queries/assessment/main/30_3_jobs.sql]: adding it to invisible columns did not hide it, removed it from the encoding. lmk if removing is not the right approach

File: src/databricks/labs/ucx/queries/assessment/main/30_3_job_details.sql (hunk 1 above)
Comment (pritishpai) [reply src/databricks/labs/ucx/queries/assessment/main/30_3_job_details.sql]: adding it to invisible columns did not hide it, removed it from the encoding. lmk if removing is not the right approach

**Review by JCZuurmond — APPROVED** [review]
LGTM

File: src/databricks/labs/ucx/queries/assessment/main/30_3_jobs.sql (hunk 4 above)
Comment (JCZuurmond) [reply src/databricks/labs/ucx/queries/assessment/main/30_3_jobs.sql]: That is interesting, I would expect: remove it from encoding and add it to invisible columns
